### ISSUE TITLE
Where do the ban data stored?

### ISSUE THREAD

**Issue by alvinzzzzz** [zachariapopcorn/discord-roblox-ban-bot#1]

**Comment by DominusTrax** [comment]
It's stored in data/db.sqlite
You sadly cannot read this with your own eyes (that I know of) although if you know JS you could add an index.html that will list out all the bans for you.

**Comment by zachariapopcorn** [comment]
Yea, I will. There's also applications that you can use to read the data from a .sqlite file. You CAN look at this with your own eyes, but it'll look messy and if you attempt to modify it, it's cause the file to corrupt
